### ISSUE TITLE
CharField missing from Comment class in Model

### ISSUE THREAD

**Issue by Pby-25** [Book4U-ECSE428/backend#12]
according to the our model description "Comment: User can write comment to a review. It the essential idea of a forum. Where the review is like a post, and comment is the replies to this post."

There doesn't seem to be an attribute to store the reply

**Comment by wzs1234566** [comment]
By 'reply' did you mean commenting a comment?

**Comment by Pby-25** [comment]
from what I understand comments are basically replies to a review? right now there isn't an attribute to store the content of those replies

**Comment by michding** [comment]
@Pby-25 True, we only have index, user, review now. 
@wzs1234566  We would need to add a "Content" attribute to it.

**Comment by wzs1234566** [comment]
@Pby-25 @michding Addressed in PR#13. Please review and approve.
